kind: pipeline
type: exec
name: app-name

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - chmod +x ./script/build.sh
      - ./script/build.sh clean
      - ./script/build.sh buildImage
      - ./script/build.sh startImage
